### ISSUE TITLE
certbot: command not found

### ISSUE THREAD

**Issue by 0xhunster** [honoki/wilson-cloud-respwnder#2]
![Screenshot_74](https://user-images.githubusercontent.com/46501627/146352365-16bc50ee-439f-4cee-9550-12c2e89ec29e.png)

**Comment by honoki** [comment]
Hi - thanks for opening this issue. I didn't include it in the documentation, but indeed you need to have `certbot` installed, which you can do with `sudo apt install certbot` (on Debian).

Can you let me know if that fixes things?

**Comment by 0xhunster** [comment]
Thanks for your reply. One request for you. could you make a video on how to install and configure it. please, please.
