### ISSUE TITLE
Missing Python package "requests" in dns container

### ISSUE THREAD

**Issue by aroly** [honoki/wilson-cloud-respwnder#3]
Hi there,

I'm trying to setup Wilson, and just noticed that when running `docker-compose` (without de daemon option):

```
Attaching to wilson-cloud-respwnder_php_1, wilson-cloud-respwnder_dns_1, wilson-cloud-respwnder_mitmdump_1, wilson-cloud-respwnder_server_1
dns_1       | Traceback (most recent call last):
dns_1       |   File "/monitor.py", line 2, in <module>
dns_1       |     import time, requests, os
dns_1       | ModuleNotFoundError: No module named 'requests'
```

It looks like the Python "requests" module is missing in the container.

Cheers,

A.

**Comment by honoki** [comment]
Thanks @aroly - I'm looking into this. Should be a straightforward fix but I'm running into other issues when reproducing locally.

**Comment by honoki** [comment]
Can you pull the latest changes and try again? :)

**Comment by aroly** [comment]
Sure: 

```
root@aro-wilson:~/wilson-cloud-respwnder# docker-compose up
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yaml", line 67, column 202
```

**Comment by honoki** [comment]
Ugh - there was a random tab character a the end of the line. Should be fixed now?

**Comment by aroly** [comment]
Sorry for the delay.

Did you remove the `settings.env` file ? :) It now complains that the file is not there... and I don't remember the variables' name in the file. 

```
# docker-compose up
ERROR: Couldn't find env file: /root/wilson-cloud-respwnder/settings.env
```

**Comment by aroly** [comment]
Hi @honoki ,

As a quick and dirty workaround, I just overwrite the `resolv.conf` file with a file containing:

```
nameserver 8.8.8.8
nameserver 1.1.1.1
```

I had to do this for the dns container and, no clue why, for the mitmdump container. The `pip install requests` for this one was also failing with some DNS related error so I tried that.

It seems to work now.

Cheers,

A.
